import type { DeviceCatalogEntry } from "@/lib/device-intelligence/catalog/apple";

export const SMART_HOME_CATALOG: DeviceCatalogEntry[] = [
  {
    id: "sonos-speaker",
    manufacturer: "Sonos",
    family: "Sonos",
    suggestedName: "Sonos speaker",
    category: "speaker",
    vendorAliases: ["Sonos"],
    hostnamePatterns: [/sonos/i],
    mdnsServices: ["_sonos._tcp", "_spotify-connect._tcp"],
    servicePorts: [1400],
  },
  {
    id: "philips-hue-bridge",
    manufacturer: "Philips Hue",
    family: "Hue Bridge",
    suggestedName: "Philips Hue Bridge",
    category: "hub",
    vendorAliases: ["Philips Hue", "Signify"],
    hostnamePatterns: [/hue/i],
    mdnsServices: ["_hue._tcp", "_hap._tcp"],
  },
  {
    id: "lutron-caseta",
    manufacturer: "Lutron",
    family: "Caséta",
    suggestedName: "Lutron Caséta Bridge",
    category: "hub",
    vendorAliases: ["Lutron"],
    hostnamePatterns: [/lutron/i],
  },
  {
    id: "tp-link-kasa",
    manufacturer: "TP-Link",
    family: "Kasa",
    suggestedName: "TP-Link Kasa device",
    category: "smart_plug",
    vendorAliases: ["TP-Link"],
    hostnamePatterns: [/kasa|tp-?link|tapo/i],
  },
  {
    id: "levoit-purifier",
    manufacturer: "Levoit",
    family: "Air Purifier",
    suggestedName: "Levoit air purifier",
    category: "air_purifier",
    vendorAliases: ["Levoit"],
    hostnamePatterns: [/levoit/i],
  },
  {
    id: "ecobee-thermostat",
    manufacturer: "Ecobee",
    family: "Thermostat",
    suggestedName: "Ecobee thermostat",
    category: "thermostat",
    vendorAliases: ["Ecobee"],
    hostnamePatterns: [/ecobee/i],
  },
  {
    id: "ring-camera",
    manufacturer: "Ring",
    family: "Ring",
    suggestedName: "Ring camera or doorbell",
    category: "camera",
    vendorAliases: ["Ring", "Amazon"],
    hostnamePatterns: [/ring/i],
  },
  {
    id: "irobot-roomba",
    manufacturer: "iRobot",
    family: "Roomba",
    suggestedName: "iRobot Roomba",
    category: "robot_vacuum",
    vendorAliases: ["iRobot"],
    hostnamePatterns: [/roomba|irobot/i],
  },
  {
    id: "roborock-vacuum",
    manufacturer: "Roborock",
    family: "Roborock",
    suggestedName: "Roborock vacuum",
    category: "robot_vacuum",
    vendorAliases: ["Roborock"],
    hostnamePatterns: [/roborock/i],
  },
];
