export const demoDevices = [
  {
    id: "demo-1",
    device_name: "MacBook Pro",
    brand: "Apple",
    category: "Computer",
    model_number: "M3 Pro",
    serial_number: "DEMO-12345",
    purchase_date: "2025-03-12",
    warranty_date: "2027-03-12",
    purchase_price: 1899,
    location: "Home Office",
    notes: "Demo device",
    photo_url: "",
  },
  {
    id: "demo-2",
    device_name: "Samsung Smart TV",
    brand: "Samsung",
    category: "TV",
    model_number: "QLED",
    serial_number: "",
    purchase_date: "2024-08-10",
    warranty_date: "",
    purchase_price: 899,
    location: "Living Room",
    notes: "Demo device",
    photo_url: "",
  },
];