import type { DemoDocument } from "@/lib/demo/types";

export const morganDocuments: DemoDocument[] = [
  { id: "doc-1", device_id: "demo-samsung-frame", document_name: "Best Buy Receipt", document_type: "Receipt", file_name: "Best Buy Receipt.pdf", created_at: "2024-06-24T12:00:00.000Z" },
  { id: "doc-2", device_id: "demo-samsung-frame", document_name: "Living Room TV Warranty", document_type: "Warranty", file_name: "Living Room TV Warranty.pdf", created_at: "2024-06-24T12:30:00.000Z" },
  { id: "doc-3", device_id: "demo-samsung-frame", document_name: "Samsung Frame Manual", document_type: "Manual", file_name: "Samsung Frame Manual.pdf", created_at: "2024-06-24T13:00:00.000Z" },
  { id: "doc-4", device_id: "demo-macbook", document_name: "AppleCare Confirmation", document_type: "Warranty", file_name: "AppleCare Confirmation.pdf", created_at: "2025-03-12T15:00:00.000Z" },
  { id: "doc-5", device_id: "demo-macbook", document_name: "MacBook Pro Invoice", document_type: "Receipt", file_name: "MacBook Pro Invoice.pdf", created_at: "2025-03-12T14:30:00.000Z" },
  { id: "doc-6", device_id: "demo-macbook", document_name: "MacBook Pro Manual", document_type: "Manual", file_name: "MacBook Pro Manual.pdf", created_at: "2025-03-12T14:00:00.000Z" },
  { id: "doc-7", device_id: "demo-studio-display", document_name: "Studio Display Receipt", document_type: "Receipt", file_name: "Studio Display Receipt.pdf", created_at: "2025-03-12T16:00:00.000Z" },
  { id: "doc-8", device_id: "demo-iphone", document_name: "iPhone 16 Pro Receipt", document_type: "Receipt", file_name: "iPhone 16 Pro Receipt.pdf", created_at: "2025-09-22T16:00:00.000Z" },
  { id: "doc-9", device_id: "demo-iphone", document_name: "AppleCare Confirmation", document_type: "Warranty", file_name: "AppleCare iPhone Confirmation.pdf", created_at: "2025-09-22T16:30:00.000Z" },
  { id: "doc-10", device_id: "demo-lg-washer", document_name: "LG Washer Manual", document_type: "Manual", file_name: "LG Washer Manual.pdf", created_at: "2026-07-20T09:00:00.000Z" },
  { id: "doc-11", device_id: "demo-lg-washer", document_name: "LG Washer Warranty", document_type: "Warranty", file_name: "LG Washer Warranty.pdf", created_at: "2022-11-05T12:00:00.000Z" },
  { id: "doc-12", device_id: "demo-lg-washer", document_name: "Appliance Store Receipt", document_type: "Receipt", file_name: "Appliance Store Receipt.pdf", created_at: "2022-11-05T11:00:00.000Z" },
  { id: "doc-13", device_id: "demo-lg-dryer", document_name: "LG Dryer Manual", document_type: "Manual", file_name: "LG Dryer Manual.pdf", created_at: "2022-11-05T12:30:00.000Z" },
  { id: "doc-14", device_id: "demo-lg-dryer", document_name: "LG Dryer Warranty", document_type: "Warranty", file_name: "LG Dryer Warranty.pdf", created_at: "2022-11-05T12:15:00.000Z" },
  { id: "doc-15", device_id: "demo-unifi-router", document_name: "Spectrum Internet Bill", document_type: "Bill", file_name: "Spectrum Internet Bill.pdf", created_at: "2026-07-01T09:00:00.000Z" },
  { id: "doc-16", device_id: "demo-unifi-router", document_name: "WiFi Password Sheet", document_type: "Reference", file_name: "WiFi Password Sheet.pdf", created_at: "2024-05-15T08:00:00.000Z" },
  { id: "doc-17", device_id: "demo-unifi-router", document_name: "UniFi Dream Router Manual", document_type: "Manual", file_name: "UniFi Dream Router Manual.pdf", created_at: "2024-05-15T08:30:00.000Z" },
  { id: "doc-18", device_id: "", document_name: "Insurance Inventory Report", document_type: "Insurance", file_name: "Insurance Inventory Report.pdf", created_at: "2026-07-07T10:00:00.000Z" },
  { id: "doc-19", device_id: "", document_name: "Home Insurance Policy", document_type: "Insurance", file_name: "Home Insurance Policy.pdf", created_at: "2026-01-10T10:00:00.000Z" },
  { id: "doc-20", device_id: "", document_name: "Floor Plan", document_type: "Reference", file_name: "Morgan Household Floor Plan.pdf", created_at: "2025-06-01T09:00:00.000Z" },
  { id: "doc-21", device_id: "demo-appletv", document_name: "Apple TV Manual", document_type: "Manual", file_name: "Apple TV Manual.pdf", created_at: "2024-10-05T10:00:00.000Z" },
  { id: "doc-22", device_id: "demo-appletv", document_name: "Apple TV Receipt", document_type: "Receipt", file_name: "Apple TV Receipt.pdf", created_at: "2024-10-05T09:30:00.000Z" },
  { id: "doc-23", device_id: "demo-sonos", document_name: "Sonos Beam Manual", document_type: "Manual", file_name: "Sonos Beam Manual.pdf", created_at: "2024-07-18T09:00:00.000Z" },
  { id: "doc-24", device_id: "demo-sonos", document_name: "Sonos Beam Receipt", document_type: "Receipt", file_name: "Sonos Beam Receipt.pdf", created_at: "2024-07-18T08:30:00.000Z" },
  { id: "doc-25", device_id: "demo-switch", document_name: "Nintendo Switch OLED Receipt", document_type: "Receipt", file_name: "Nintendo Switch OLED Receipt.pdf", created_at: "2025-02-14T14:00:00.000Z" },
  { id: "doc-26", device_id: "demo-ps5", document_name: "PlayStation 5 Receipt", document_type: "Receipt", file_name: "PlayStation 5 Receipt.pdf", created_at: "2024-11-28T18:00:00.000Z" },
  { id: "doc-27", device_id: "demo-xbox", document_name: "Xbox Series X Receipt", document_type: "Receipt", file_name: "Xbox Series X Receipt.pdf", created_at: "2024-12-20T14:00:00.000Z" },
  { id: "doc-28", device_id: "demo-canon-printer", document_name: "Canon Printer Manual", document_type: "Manual", file_name: "Canon Printer Manual.pdf", created_at: "2023-08-15T10:00:00.000Z" },
  { id: "doc-29", device_id: "demo-synology", document_name: "Synology NAS Setup Guide", document_type: "Setup Guide", file_name: "Synology NAS Setup Guide.pdf", created_at: "2024-02-10T11:00:00.000Z" },
  { id: "doc-30", device_id: "demo-synology", document_name: "Synology NAS Receipt", document_type: "Receipt", file_name: "Synology NAS Receipt.pdf", created_at: "2024-02-10T10:30:00.000Z" },
  { id: "doc-31", device_id: "demo-samsung-fridge", document_name: "Samsung Refrigerator Manual", document_type: "Manual", file_name: "Samsung Refrigerator Manual.pdf", created_at: "2023-02-18T14:00:00.000Z" },
  { id: "doc-32", device_id: "demo-samsung-fridge", document_name: "Samsung Care+ Warranty", document_type: "Warranty", file_name: "Samsung Care+ Warranty.pdf", created_at: "2023-02-18T14:30:00.000Z" },
  { id: "doc-33", device_id: "demo-echo-show", document_name: "Echo Show Manual", document_type: "Manual", file_name: "Echo Show Manual.pdf", created_at: "2024-04-02T11:00:00.000Z" },
  { id: "doc-34", device_id: "demo-robot-vacuum", document_name: "Roborock S8 Manual", document_type: "Manual", file_name: "Roborock S8 Manual.pdf", created_at: "2025-04-08T10:00:00.000Z" },
  { id: "doc-35", device_id: "demo-robot-vacuum", document_name: "Roborock Purchase Receipt", document_type: "Receipt", file_name: "Roborock Purchase Receipt.pdf", created_at: "2025-04-08T09:30:00.000Z" },
  { id: "doc-36", device_id: "demo-air-purifier", document_name: "Dyson Purifier Manual", document_type: "Manual", file_name: "Dyson Purifier Manual.pdf", created_at: "2024-01-20T12:00:00.000Z" },
  { id: "doc-37", device_id: "demo-lg-oled", document_name: "LG OLED Receipt", document_type: "Receipt", file_name: "LG OLED Receipt.pdf", created_at: "2025-01-15T11:00:00.000Z" },
  { id: "doc-38", device_id: "demo-lg-oled", document_name: "LG OLED Warranty", document_type: "Warranty", file_name: "LG OLED Warranty.pdf", created_at: "2025-01-15T11:30:00.000Z" },
  { id: "doc-39", device_id: "demo-ring", document_name: "Ring Doorbell Setup Guide", document_type: "Setup Guide", file_name: "Ring Doorbell Setup Guide.pdf", created_at: "2024-03-22T13:00:00.000Z" },
  { id: "doc-40", device_id: "demo-ring", document_name: "Ring Protect Plan", document_type: "Warranty", file_name: "Ring Protect Plan.pdf", created_at: "2024-03-22T13:30:00.000Z" },
  { id: "doc-41", device_id: "demo-smart-lock", document_name: "Yale Smart Lock Manual", document_type: "Manual", file_name: "Yale Smart Lock Manual.pdf", created_at: "2024-09-14T10:00:00.000Z" },
  { id: "doc-42", device_id: "demo-nest", document_name: "Nest Thermostat Manual", document_type: "Manual", file_name: "Nest Thermostat Manual.pdf", created_at: "2023-09-10T09:00:00.000Z" },
  { id: "doc-43", device_id: "demo-cameras", document_name: "Arlo Camera Manual", document_type: "Manual", file_name: "Arlo Camera Manual.pdf", created_at: "2024-06-01T10:00:00.000Z" },
  { id: "doc-44", device_id: "demo-cameras", document_name: "Arlo Purchase Receipt", document_type: "Receipt", file_name: "Arlo Purchase Receipt.pdf", created_at: "2024-06-01T09:30:00.000Z" },
  { id: "doc-45", device_id: "demo-unifi-ap", document_name: "UniFi U6 Pro Manual", document_type: "Manual", file_name: "UniFi U6 Pro Manual.pdf", created_at: "2024-05-15T09:00:00.000Z" },
  { id: "doc-46", device_id: "demo-ps5", document_name: "PS5 Extended Warranty", document_type: "Warranty", file_name: "PS5 Extended Warranty.pdf", created_at: "2024-11-28T18:30:00.000Z" },
  { id: "doc-47", device_id: "demo-xbox", document_name: "Xbox Game Pass Invoice", document_type: "Receipt", file_name: "Xbox Game Pass Invoice.pdf", created_at: "2024-12-20T14:30:00.000Z" },
];
