import type { DemoSubscription } from "@/lib/demo/types";

export const morganSubscriptions: DemoSubscription[] = [
  {
    id: "demo-sub-netflix",
    service_name: "Netflix",
    name: "Netflix",
    category: "Streaming",
    monthly_cost: 22.99,
    renewal_date: "2026-08-07",
    billing_cycle: "Monthly",
    notes: "Premium plan for living room and bedroom TVs.",
  },
  {
    id: "demo-sub-disney",
    service_name: "Disney+",
    name: "Disney+",
    category: "Streaming",
    monthly_cost: 13.99,
    renewal_date: "2026-08-12",
    billing_cycle: "Monthly",
    notes: "Family streaming for kids and movie nights.",
  },
  {
    id: "demo-sub-apple-one",
    service_name: "Apple One",
    name: "Apple One",
    category: "Bundle",
    monthly_cost: 29.95,
    renewal_date: "2026-08-03",
    billing_cycle: "Monthly",
    notes: "iCloud+, Apple Music, Apple TV+, and Apple Arcade.",
  },
  {
    id: "demo-sub-microsoft",
    service_name: "Microsoft 365",
    name: "Microsoft 365",
    category: "Productivity",
    monthly_cost: 9.99,
    renewal_date: "2026-08-22",
    billing_cycle: "Monthly",
    notes: "Office apps and OneDrive for the household.",
  },
  {
    id: "demo-sub-adobe",
    service_name: "Adobe Creative Cloud",
    name: "Adobe Creative Cloud",
    category: "Software",
    monthly_cost: 59.99,
    renewal_date: "2026-08-15",
    billing_cycle: "Monthly",
    notes: "Photography and design tools for Alex's work.",
  },
  {
    id: "demo-sub-google-one",
    service_name: "Google One",
    name: "Google One",
    category: "Cloud Storage",
    monthly_cost: 9.99,
    renewal_date: "2026-08-18",
    billing_cycle: "Monthly",
    notes: "2 TB shared storage for Nest and Google Photos.",
  },
  {
    id: "demo-sub-ring",
    service_name: "Ring Protect",
    name: "Ring Protect Plus",
    category: "Security",
    monthly_cost: 9.99,
    renewal_date: "2026-08-05",
    billing_cycle: "Monthly",
    notes: "Video recording for Ring Doorbell and Arlo cameras.",
  },
  {
    id: "demo-sub-youtube",
    service_name: "YouTube Premium",
    name: "YouTube Premium",
    category: "Streaming",
    monthly_cost: 13.99,
    renewal_date: "2026-08-25",
    billing_cycle: "Monthly",
    notes: "Ad-free YouTube for the whole family.",
  },
];
