import type { DemoDocument } from "@/lib/demo/types";

export const morganDocuments: DemoDocument[] = [
  {
    id: "demo-doc-1",
    device_id: "demo-macbook",
    document_name: "AppleCare+ Receipt",
    document_type: "Receipt",
    file_name: "applecare-receipt.pdf",
    created_at: "2025-03-12T15:00:00.000Z",
  },
  {
    id: "demo-doc-2",
    device_id: "demo-macbook",
    document_name: "MacBook Purchase Invoice",
    document_type: "Receipt",
    file_name: "macbook-purchase-invoice.pdf",
    created_at: "2025-03-12T14:30:00.000Z",
  },
  {
    id: "demo-doc-3",
    device_id: "demo-iphone",
    document_name: "iPhone 16 Pro Receipt",
    document_type: "Receipt",
    file_name: "iphone-16-pro-receipt.pdf",
    created_at: "2025-09-22T16:00:00.000Z",
  },
  {
    id: "demo-doc-4",
    device_id: "demo-samsung-frame",
    document_name: "Best Buy Receipt",
    document_type: "Receipt",
    file_name: "best-buy-frame-tv-receipt.pdf",
    created_at: "2024-06-24T12:00:00.000Z",
  },
  {
    id: "demo-doc-5",
    device_id: "demo-samsung-frame",
    document_name: "Samsung Warranty Certificate",
    document_type: "Warranty",
    file_name: "samsung-warranty.pdf",
    created_at: "2024-06-24T12:30:00.000Z",
  },
  {
    id: "demo-doc-6",
    device_id: "demo-lg-oled",
    document_name: "LG OLED Purchase Invoice",
    document_type: "Receipt",
    file_name: "lg-oled-invoice.pdf",
    created_at: "2025-01-15T11:00:00.000Z",
  },
  {
    id: "demo-doc-7",
    device_id: "demo-ps5",
    document_name: "PlayStation 5 Receipt",
    document_type: "Receipt",
    file_name: "ps5-receipt.pdf",
    created_at: "2024-11-28T18:00:00.000Z",
  },
  {
    id: "demo-doc-8",
    device_id: "demo-xbox",
    document_name: "Xbox Series X Receipt",
    document_type: "Receipt",
    file_name: "xbox-series-x-receipt.pdf",
    created_at: "2024-12-20T14:00:00.000Z",
  },
  {
    id: "demo-doc-9",
    device_id: "demo-appletv",
    document_name: "Apple TV User Manual",
    document_type: "Manual",
    file_name: "apple-tv-manual.pdf",
    created_at: "2024-10-05T10:00:00.000Z",
  },
  {
    id: "demo-doc-10",
    device_id: "demo-sonos",
    document_name: "Sonos Beam Manual",
    document_type: "Manual",
    file_name: "sonos-beam-manual.pdf",
    created_at: "2024-07-18T09:00:00.000Z",
  },
  {
    id: "demo-doc-11",
    device_id: "demo-ring",
    document_name: "Ring Doorbell Setup Guide",
    document_type: "Setup Guide",
    file_name: "ring-doorbell-setup.pdf",
    created_at: "2024-03-22T13:00:00.000Z",
  },
  {
    id: "demo-doc-12",
    device_id: "demo-canon-printer",
    document_name: "Canon Printer Manual",
    document_type: "Manual",
    file_name: "canon-pixma-manual.pdf",
    created_at: "2023-08-15T10:00:00.000Z",
  },
  {
    id: "demo-doc-13",
    device_id: "demo-unifi-router",
    document_name: "WiFi Password Sheet",
    document_type: "Reference",
    file_name: "wifi-password-sheet.pdf",
    created_at: "2024-05-15T08:00:00.000Z",
  },
  {
    id: "demo-doc-14",
    device_id: "demo-unifi-router",
    document_name: "Internet Bill — July 2026",
    document_type: "Bill",
    file_name: "internet-bill-july-2026.pdf",
    created_at: "2026-07-01T09:00:00.000Z",
  },
  {
    id: "demo-doc-15",
    device_id: "demo-synology",
    document_name: "Synology NAS Setup Guide",
    document_type: "Setup Guide",
    file_name: "synology-setup-guide.pdf",
    created_at: "2024-02-10T11:00:00.000Z",
  },
  {
    id: "demo-doc-16",
    device_id: "demo-samsung-fridge",
    document_name: "Samsung Refrigerator Manual",
    document_type: "Manual",
    file_name: "samsung-fridge-manual.pdf",
    created_at: "2023-02-18T14:00:00.000Z",
  },
  {
    id: "demo-doc-17",
    device_id: "demo-lg-washer",
    document_name: "LG Washer Warranty",
    document_type: "Warranty",
    file_name: "lg-washer-warranty.pdf",
    created_at: "2022-11-05T12:00:00.000Z",
  },
  {
    id: "demo-doc-18",
    device_id: "",
    document_name: "Home Insurance Inventory",
    document_type: "Insurance",
    file_name: "home-insurance-inventory.pdf",
    created_at: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "demo-doc-19",
    device_id: "",
    document_name: "Floor Plan",
    document_type: "Reference",
    file_name: "morgan-household-floor-plan.pdf",
    created_at: "2025-06-01T09:00:00.000Z",
  },
  {
    id: "demo-doc-20",
    device_id: "demo-hp-laptop",
    document_name: "HP Laptop Purchase Invoice",
    document_type: "Receipt",
    file_name: "hp-laptop-invoice.pdf",
    created_at: "2023-05-20T15:00:00.000Z",
  },
];
