import { getDemoImagePathForDeviceId } from "@/lib/devices/demoDeviceImages";
import type { DemoDevice } from "@/lib/demo/types";

type DeviceSeed = Omit<
  DemoDevice,
  | "online"
  | "last_seen_at"
  | "ip_address"
  | "mac_address"
  | "manufacturer"
  | "discovery_source"
  | "photo_url"
  | "demo_image"
> & {
  online?: boolean;
  ip_suffix?: number;
};

function buildDevice(seed: DeviceSeed): DemoDevice {
  const ipSuffix = seed.ip_suffix ?? 20;
  const online = seed.online ?? true;
  const demoImage =
    getDemoImagePathForDeviceId(seed.id) ?? "";

  return {
    ...seed,
    online,
    last_seen_at: online
      ? new Date().toISOString()
      : "2026-07-19T08:15:00.000Z",
    ip_address: ipSuffix > 0 ? `192.168.1.${ipSuffix}` : "",
    mac_address:
      ipSuffix > 0
        ? `AA:BB:CC:${String(ipSuffix).padStart(2, "0")}:01:02`
        : "",
    manufacturer: seed.brand,
    discovery_source: "Network Scan",
    photo_url: "",
    demo_image: demoImage,
  };
}

export const morganDevices: DemoDevice[] = [
  buildDevice({
    id: "demo-samsung-frame",
    device_name: "Samsung Frame TV",
    brand: "Samsung",
    category: "TV",
    model_number: '65" The Frame (2024)',
    serial_number: "SAM-FRM-65-8842",
    purchase_date: "2024-06-24",
    warranty_date: "2026-08-18",
    purchase_price: 1899,
    location: "Living Room",
    notes:
      "Art mode enabled in the living room. Extended Best Buy protection expires in 28 days.",
    ip_suffix: 25,
  }),
  buildDevice({
    id: "demo-appletv",
    device_name: "Apple TV 4K",
    brand: "Apple",
    category: "Streaming",
    model_number: "128GB (3rd Gen)",
    serial_number: "ATV4K-128-55102",
    purchase_date: "2024-10-05",
    warranty_date: "2026-10-05",
    purchase_price: 149,
    location: "Living Room",
    notes: "Primary streaming hub for the Samsung Frame TV.",
    ip_suffix: 26,
  }),
  buildDevice({
    id: "demo-sonos",
    device_name: "Sonos Beam",
    brand: "Sonos",
    category: "Audio",
    model_number: "Gen 2 Soundbar",
    serial_number: "SONOS-BEAM-2201",
    purchase_date: "2024-07-18",
    warranty_date: "2026-07-18",
    purchase_price: 499,
    location: "Living Room",
    notes: "Soundbar paired with the Frame TV. Alexa voice control enabled.",
    ip_suffix: 28,
  }),
  buildDevice({
    id: "demo-switch",
    device_name: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "Gaming",
    model_number: "OLED Model",
    serial_number: "NSW-OLED-90331",
    purchase_date: "2025-02-14",
    warranty_date: "2027-02-14",
    purchase_price: 349,
    location: "Living Room",
    notes: "Dock stays in the media console. Joy-Cons stored in the drawer.",
    ip_suffix: 42,
  }),
  buildDevice({
    id: "demo-ps5",
    device_name: "PlayStation 5",
    brand: "Sony",
    category: "Gaming",
    model_number: "Disc Edition",
    serial_number: "PS5-DISC-77201",
    purchase_date: "2024-11-28",
    warranty_date: "2026-11-28",
    purchase_price: 499,
    location: "Living Room",
    notes: "Connected to the Frame TV. DualSense charging dock in the cabinet.",
    ip_suffix: 40,
  }),
  buildDevice({
    id: "demo-xbox",
    device_name: "Xbox Series X",
    brand: "Microsoft",
    category: "Gaming",
    model_number: "Series X",
    serial_number: "XSX-2024-44102",
    purchase_date: "2024-12-20",
    warranty_date: "2026-12-20",
    purchase_price: 499,
    location: "Living Room",
    notes: "Game Pass Ultimate active. Shares the Frame TV with the PS5.",
    ip_suffix: 41,
  }),
  buildDevice({
    id: "demo-macbook",
    device_name: "MacBook Pro",
    brand: "Apple",
    category: "Computer",
    model_number: "14-inch M3 Pro",
    serial_number: "C02ZK0A1MD6T",
    purchase_date: "2025-03-12",
    warranty_date: "2027-03-12",
    purchase_price: 1999,
    location: "Office",
    notes:
      "Alex's primary work computer. AppleCare+ through March 2027. Time Machine backup to Synology nightly.",
    ip_suffix: 14,
  }),
  buildDevice({
    id: "demo-studio-display",
    device_name: "Studio Display",
    brand: "Apple",
    category: "Monitor",
    model_number: '27" 5K',
    serial_number: "STD-27-5K-4421",
    purchase_date: "2025-03-12",
    warranty_date: "2027-03-12",
    purchase_price: 1599,
    location: "Office",
    notes: "Paired with the MacBook Pro on the standing desk.",
    ip_suffix: 16,
  }),
  buildDevice({
    id: "demo-canon-printer",
    device_name: "Canon Printer",
    brand: "Canon",
    category: "Printer",
    model_number: "PIXMA TR8620a",
    serial_number: "CANON-TR8620-1102",
    purchase_date: "2023-08-15",
    warranty_date: "2024-08-15",
    purchase_price: 199,
    location: "Office",
    notes: "All-in-one inkjet for school forms and shipping labels.",
    ip_suffix: 31,
    online: false,
  }),
  buildDevice({
    id: "demo-unifi-router",
    device_name: "UniFi Dream Router",
    brand: "Ubiquiti",
    category: "Network Equipment",
    model_number: "UDR",
    serial_number: "UDR-2024-1102",
    purchase_date: "2024-05-15",
    warranty_date: "2026-05-15",
    purchase_price: 199,
    location: "Office",
    notes: "Main home router on the office shelf. Firmware 3.2.7 available.",
    ip_suffix: 1,
  }),
  buildDevice({
    id: "demo-synology",
    device_name: "Synology NAS",
    brand: "Synology",
    category: "Storage",
    model_number: "DS923+",
    serial_number: "SYN-DS923-4401",
    purchase_date: "2024-02-10",
    warranty_date: "2027-02-10",
    purchase_price: 599,
    location: "Office",
    notes:
      "Family photos, documents, and Time Machine backups. RAID 1 with 8 TB drives.",
    ip_suffix: 10,
  }),
  buildDevice({
    id: "demo-iphone",
    device_name: "iPhone 16 Pro",
    brand: "Apple",
    category: "Mobile",
    model_number: "256GB Natural Titanium",
    serial_number: "F17D9K2LQ8M4",
    purchase_date: "2025-09-22",
    warranty_date: "2027-09-22",
    purchase_price: 1199,
    location: "Office",
    notes: "Primary mobile device. AppleCare+ and iCloud backup enabled.",
    ip_suffix: 19,
  }),
  buildDevice({
    id: "demo-samsung-fridge",
    device_name: "Samsung Refrigerator",
    brand: "Samsung",
    category: "Appliance",
    model_number: "Bespoke 4-Door Flex",
    serial_number: "SAM-RF29-9901",
    purchase_date: "2023-02-18",
    warranty_date: "2028-02-18",
    purchase_price: 3299,
    location: "Kitchen",
    notes: "Family Hub display. Extended Samsung Care+ warranty on file.",
    ip_suffix: 0,
    online: false,
  }),
  buildDevice({
    id: "demo-echo-show",
    device_name: "Echo Show",
    brand: "Amazon",
    category: "Smart Home",
    model_number: '15"',
    serial_number: "ECHO-SHOW15-2201",
    purchase_date: "2024-04-02",
    warranty_date: "2025-04-02",
    purchase_price: 279,
    location: "Kitchen",
    notes: "Kitchen hub for timers, recipes, and Ring camera feeds.",
    ip_suffix: 55,
  }),
  buildDevice({
    id: "demo-lg-washer",
    device_name: "LG Washer",
    brand: "LG",
    category: "Appliance",
    model_number: "WM4000HWA",
    serial_number: "LG-WM4000-2201",
    purchase_date: "2022-11-05",
    warranty_date: "2027-11-05",
    purchase_price: 1099,
    location: "Laundry Room",
    notes: "Front-load washer with ThinQ app. Manual added yesterday.",
    ip_suffix: 0,
    online: false,
  }),
  buildDevice({
    id: "demo-lg-dryer",
    device_name: "LG Dryer",
    brand: "LG",
    category: "Appliance",
    model_number: "DLEX4000W",
    serial_number: "LG-DLEX4000-2202",
    purchase_date: "2022-11-05",
    warranty_date: "2027-11-05",
    purchase_price: 999,
    location: "Laundry Room",
    notes: "Matching LG dryer installed alongside the washer.",
    ip_suffix: 0,
    online: false,
  }),
  buildDevice({
    id: "demo-robot-vacuum",
    device_name: "Robot Vacuum Dock",
    brand: "Roborock",
    category: "Smart Home",
    model_number: "S8 Pro Ultra",
    serial_number: "RB-S8PU-1102",
    purchase_date: "2025-04-08",
    warranty_date: "2027-04-08",
    purchase_price: 1599,
    location: "Bedroom",
    notes: "Self-emptying dock in the primary bedroom closet. Daily 7 AM schedule.",
    ip_suffix: 53,
  }),
  buildDevice({
    id: "demo-air-purifier",
    device_name: "Air Purifier",
    brand: "Dyson",
    category: "Appliance",
    model_number: "Purifier Cool TP07",
    serial_number: "DYS-TP07-3301",
    purchase_date: "2024-01-20",
    warranty_date: "2025-01-20",
    purchase_price: 549,
    location: "Bedroom",
    notes: "HEPA filter replaced every 12 months. Auto mode overnight.",
    ip_suffix: 0,
    online: false,
  }),
  buildDevice({
    id: "demo-lg-oled",
    device_name: "LG OLED TV",
    brand: "LG",
    category: "TV",
    model_number: '65" C4 OLED',
    serial_number: "LG-OLED-C4-2291",
    purchase_date: "2025-01-15",
    warranty_date: "2027-01-15",
    purchase_price: 1799,
    location: "Bedroom",
    notes: "Wall-mounted in the primary bedroom.",
    ip_suffix: 27,
  }),
  buildDevice({
    id: "demo-ring",
    device_name: "Ring Doorbell",
    brand: "Ring",
    category: "Security",
    model_number: "Video Doorbell Pro 2",
    serial_number: "RING-VDBP2-33102",
    purchase_date: "2024-03-22",
    warranty_date: "2026-03-22",
    purchase_price: 249,
    location: "Entryway",
    notes: "Hardwired at the front door. Firmware update available.",
    ip_suffix: 51,
  }),
  buildDevice({
    id: "demo-smart-lock",
    device_name: "Yale Smart Lock",
    brand: "Yale",
    category: "Smart Home",
    model_number: "Assure Lock 2",
    serial_number: "YALE-AL2-2201",
    purchase_date: "2024-09-14",
    warranty_date: "2025-09-14",
    purchase_price: 279,
    location: "Entryway",
    notes: "Apple Home Key enabled. Paired with Ring Doorbell.",
    ip_suffix: 54,
  }),
  buildDevice({
    id: "demo-nest",
    device_name: "Nest Thermostat",
    brand: "Google",
    category: "Smart Home",
    model_number: "Learning Thermostat (4th Gen)",
    serial_number: "NEST-LRN-88401",
    purchase_date: "2023-09-10",
    warranty_date: "2025-09-10",
    purchase_price: 249,
    location: "Hallway",
    notes: "Controls main-floor HVAC. Google Home routines integrated.",
    ip_suffix: 50,
  }),
  buildDevice({
    id: "demo-unifi-ap",
    device_name: "UniFi Access Point",
    brand: "Ubiquiti",
    category: "Network Equipment",
    model_number: "U6 Pro",
    serial_number: "U6PRO-2024-2201",
    purchase_date: "2024-05-15",
    warranty_date: "2025-05-15",
    purchase_price: 149,
    location: "Hallway",
    notes: "Ceiling-mounted access point. Excellent whole-home coverage.",
    ip_suffix: 2,
  }),
  buildDevice({
    id: "demo-cameras",
    device_name: "Security Cameras",
    brand: "Arlo",
    category: "Security",
    model_number: "Pro 5S (3-Pack)",
    serial_number: "ARLO-PRO5S-3301",
    purchase_date: "2024-06-01",
    warranty_date: "2026-06-01",
    purchase_price: 599,
    location: "Garage",
    notes: "Three outdoor cameras: driveway, backyard, and garage.",
    ip_suffix: 52,
  }),
];
