import {
  CircleAlert,
  FileText,
  Laptop,
  Radar,
  ShieldCheck,
  Sparkles,
  Users,
  Wrench,
} from "lucide-react";

import { MORGAN_HOUSEHOLD } from "@/lib/demo/morganHousehold";
import type { VaultNotification } from "@/lib/notifications/types";

export const demoNotifications: VaultNotification[] = [
  {
    id: "demo-warranty",
    title: "Samsung Frame TV warranty expires in 28 days",
    description:
      "Extended Best Buy coverage expires soon. Review before it ends.",
    timestamp: new Date().toISOString(),
    priority: "high",
    category: "warranty",
    type: "warning",
    href: "/warranties",
    actionLabel: "Review",
    dismissible: true,
    icon: ShieldCheck,
  },
  {
    id: "demo-maintenance",
    title: "UniFi Dream Router firmware update available",
    description:
      "Version 3.2.7 is ready to install during your next maintenance window.",
    timestamp: new Date().toISOString(),
    priority: "normal",
    category: "maintenance",
    type: "info",
    href: "/maintenance",
    actionLabel: "View Tasks",
    dismissible: true,
    icon: Wrench,
  },
  {
    id: "demo-network",
    title: "18 devices connected to Morgan-Home-5G",
    description:
      "Network scan shows excellent signal health across the home.",
    timestamp: new Date().toISOString(),
    priority: "normal",
    category: "network",
    type: "success",
    href: "/network",
    actionLabel: "View Network",
    dismissible: true,
    icon: Radar,
  },
  {
    id: "demo-family",
    title: "Jamie Morgan joined the household",
    description:
      "A family member accepted their invitation to the shared vault.",
    timestamp: new Date().toISOString(),
    priority: "normal",
    category: "family",
    type: "success",
    href: "/family",
    actionLabel: "View Household",
    dismissible: true,
    icon: Users,
  },
  {
    id: "demo-insight",
    title: "Living Room contains the most entertainment value",
    description:
      "TVs, consoles, and audio equipment account for 34% of recorded value.",
    timestamp: new Date().toISOString(),
    priority: "low",
    category: "insight",
    type: "insight",
    href: "/home",
    actionLabel: "View Rooms",
    dismissible: true,
    icon: Sparkles,
  },
  {
    id: "demo-security",
    title: "Two devices missing warranty information",
    description:
      "Add warranty details for the Dyson Vacuum and Robot Vacuum.",
    timestamp: new Date().toISOString(),
    priority: "normal",
    category: "security",
    type: "info",
    href: "/warranties",
    actionLabel: "Review Warranties",
    dismissible: true,
    icon: CircleAlert,
  },
  {
    id: "demo-receipt",
    title: "Receipt uploaded for Samsung Refrigerator",
    description:
      "Extended warranty documentation added yesterday.",
    timestamp: new Date().toISOString(),
    priority: "normal",
    category: "backup",
    type: "info",
    href: "/documents",
    actionLabel: "View Documents",
    dismissible: true,
    icon: FileText,
  },
  {
    id: "demo-device",
    title: `Welcome to the ${MORGAN_HOUSEHOLD.name}`,
    description:
      "Explore 23 organized devices, documents, and warranties throughout the home.",
    timestamp: new Date().toISOString(),
    priority: "low",
    category: "device",
    type: "success",
    href: "/devices",
    actionLabel: "Browse Devices",
    dismissible: true,
    icon: Laptop,
  },
];
