import type { VaultActivityEvent } from "@/lib/activity/types";
import { MORGAN_HOUSEHOLD } from "@/lib/demo/morganHousehold";

export const demoActivityEvents: VaultActivityEvent[] = [
  {
    id: "demo-activity-1",
    activityType: "device.added",
    title: "MacBook Pro added to vault",
    description:
      "Primary work computer saved with AppleCare+ coverage.",
    occurredAt: "2026-07-20T14:20:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: "demo-macbook",
    entityId: "demo-macbook",
    source: "derived",
  },
  {
    id: "demo-activity-2",
    activityType: "receipt.uploaded",
    title: "Receipt uploaded for Samsung Frame TV",
    description:
      "Best Buy purchase receipt attached to the device record.",
    occurredAt: "2026-07-19T10:05:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: "demo-samsung-frame",
    entityId: "demo-doc-4",
    source: "local",
  },
  {
    id: "demo-activity-3",
    activityType: "maintenance.completed",
    title: "LG washer deep clean completed",
    description:
      "Tub Clean cycle finished and logged in maintenance.",
    occurredAt: "2026-07-18T18:40:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: "demo-lg-washer",
    entityId: "demo-maint-lg",
    source: "derived",
  },
  {
    id: "demo-activity-4",
    activityType: "network.scan.completed",
    title: "Network scan completed",
    description:
      "Found 18 connected devices across the Morgan home network.",
    occurredAt: "2026-07-17T09:15:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: null,
    entityId: "demo-scan-1",
    source: "derived",
  },
  {
    id: "demo-activity-5",
    activityType: "family.member.invited",
    title: "jamie.morgan@example.com invited to household",
    description:
      "Family invitation sent with member access.",
    occurredAt: "2026-07-16T16:00:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: null,
    entityId: "demo-invite-1",
    source: "local",
  },
  {
    id: "demo-activity-6",
    activityType: "room.created",
    title: "Utility Closet room created",
    description:
      "Network and laundry devices grouped into Utility Closet.",
    occurredAt: "2026-07-15T11:30:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: null,
    entityId: "demo-room-utility",
    source: "local",
  },
  {
    id: "demo-activity-7",
    activityType: "subscription.added",
    title: "Apple One subscription added",
    description:
      "Family bundle recorded in the vault.",
    occurredAt: "2026-07-14T08:00:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: null,
    entityId: "demo-sub-apple-one",
    source: "local",
  },
  {
    id: "demo-activity-8",
    activityType: "warranty.expiring",
    title: "Samsung Frame TV warranty expiring soon",
    description:
      "Extended coverage ends in 28 days.",
    occurredAt: "2026-07-13T12:00:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: "demo-samsung-frame",
    entityId: "demo-samsung-frame",
    source: "derived",
  },
  {
    id: "demo-activity-9",
    activityType: "maintenance.scheduled",
    title: "UniFi Dream Router firmware update available",
    description:
      "Version 3.2.7 ready to install.",
    occurredAt: "2026-07-12T09:30:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: "demo-unifi-router",
    entityId: "demo-unifi-router",
    source: "derived",
  },
  {
    id: "demo-activity-10",
    activityType: "receipt.uploaded",
    title: "Samsung refrigerator warranty receipt uploaded",
    description:
      "Extended 5-year Samsung Care+ documentation added.",
    occurredAt: "2026-07-19T11:00:00.000Z",
    userId: "demo-user",
    userDisplayName: MORGAN_HOUSEHOLD.fullName,
    householdId: "demo-household",
    deviceId: "demo-samsung-fridge",
    entityId: "demo-doc-fridge",
    source: "local",
  },
];
