"use client";

import jsPDF from "jspdf";
import { supabase } from "@/lib/supabase";
import { calculateTechnologyScore } from "@/lib/calculateTechnologyScore";

export default function DownloadAuditPdfButton() {
  async function downloadPdf() {
    const { data: devices } = await supabase.from("devices").select("*");
    const { data: subscriptions } = await supabase.from("subscriptions").select("*");
    const { data: documents } = await supabase.from("documents").select("*");
    const { data: network } = await supabase
      .from("network_info")
      .select("*")
      .limit(1)
      .maybeSingle();

    const deviceList = devices ?? [];
    const subscriptionList = subscriptions ?? [];
    const documentList = documents ?? [];

    const score = calculateTechnologyScore(deviceList);

    const totalValue = deviceList.reduce(
      (sum, device) => sum + Number(device.purchase_price || 0),
      0
    );

    const monthlySpend = subscriptionList.reduce(
      (sum, sub) => sum + Number(sub.monthly_cost || 0),
      0
    );

    const missingSerials = deviceList.filter((d) => !d.serial_number);
    const missingWarranties = deviceList.filter((d) => !d.warranty_date);
    const missingPhotos = deviceList.filter((d) => !d.photo_url);

    const pdf = new jsPDF();

    pdf.setFillColor(15, 23, 42);
    pdf.rect(0, 0, 210, 40, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(22);
    pdf.text("Home Tech Vault", 14, 18);

    pdf.setFontSize(11);
    pdf.text("Professional Technology Audit Report", 14, 29);

    pdf.setTextColor(15, 23, 42);
    pdf.setFontSize(18);
    pdf.text("Technology Overview", 14, 55);

    pdf.setFontSize(12);
    pdf.text(`Technology Score: ${score}/100`, 14, 70);
    pdf.text(`Devices Tracked: ${deviceList.length}`, 14, 80);
    pdf.text(`Documents Stored: ${documentList.length}`, 14, 90);
    pdf.text(`Estimated Technology Value: $${totalValue.toFixed(2)}`, 14, 100);
    pdf.text(`Monthly Subscription Spend: $${monthlySpend.toFixed(2)}`, 14, 110);
    pdf.text(`Yearly Subscription Spend: $${(monthlySpend * 12).toFixed(2)}`, 14, 120);
    pdf.text(`Network Status: ${network ? "Documented" : "Missing"}`, 14, 130);

    pdf.setFontSize(18);
    pdf.text("Items Needing Attention", 14, 155);

    pdf.setFontSize(12);
    pdf.text(`Missing Serial Numbers: ${missingSerials.length}`, 14, 170);
    pdf.text(`Missing Warranty Dates: ${missingWarranties.length}`, 14, 180);
    pdf.text(`Missing Device Photos: ${missingPhotos.length}`, 14, 190);

    pdf.setFontSize(18);
    pdf.text("Recommended Next Steps", 14, 215);

    pdf.setFontSize(11);
    const recommendations = [
      "Add missing serial numbers for insurance and warranty claims.",
      "Upload receipts and warranty documents for high-value devices.",
      "Add photos to improve your visual inventory.",
      "Keep subscription renewal dates updated.",
      "Review your network information twice per year.",
    ];

    recommendations.forEach((item, index) => {
      pdf.text(`• ${item}`, 14, 230 + index * 9);
    });

    pdf.setFontSize(9);
    pdf.setTextColor(100, 116, 139);
    pdf.text(
      `Generated by Home Tech Vault on ${new Date().toLocaleDateString()}`,
      14,
      285
    );

    pdf.save("home-tech-vault-audit.pdf");
  }

  return (
    <button
      onClick={downloadPdf}
      className="bg-blue-950 text-white px-6 py-3 rounded-xl"
    >
      Download Professional PDF
    </button>
  );
}